function [fx, fy] = getInterpolatingFun()

pins = getPinData();
load('tactip-benchmarks\trainDepthVideo05012246/expt.mat')
load('tactip-benchmarks\trainDepthVideo05012246/expt_mapping.mat')
cam_reference = Expt.pinPositions';
cam_reference = cam_reference(:,expt_mapping);

% interpolation
fx = scatteredInterpolant(pins.original_coordinates(1,:)',...
                 pins.original_coordinates(2,:)',...
                 pins.original_coordinates(3,:)',...
                 cam_reference(1,:)', 'natural' ,'linear');
fy = scatteredInterpolant(pins.original_coordinates(1,:)',...
                 pins.original_coordinates(2,:)',...
                 pins.original_coordinates(3,:)',...
                 cam_reference(2,:)', 'natural' ,'linear');
end
